House Of Young/HOY/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
import debug_toolbar


urlpatterns = [
        path('admin/', admin.site.urls),
        path('', include('core.urls')),
        path('api/', include('core.api.urls')),
        path('sessions/', include('sessions.urls')),
        path('__debug__/', include('debug_toolbar.urls')),
    ]
# if settings.DEBUG:

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

House Of Young/core/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EventViewSet





event_router = DefaultRouter()
event_router.register(r'event', EventViewSet, basename='event')

urlpatterns = [
    path('', include(event_router.urls)),
]

House Of Young/core/urls.py
from django.urls import path
from .views import index, blog, blog_detail, blog_list, event, event_detail, about, contact

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('blog/', blog, name='blog'),
    path('blog/<int:blog_id>/', blog_detail, name='blog_detail'),
    path('blog_list/', blog_list, name='blog_list'),
    path('event/', event, name='event'),
    path('event/<int:event_id>/<slug:slug>/', event_detail, name='event_detail'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

House Of Young/sessions/urls.py
from django.urls import path
from .views import register, activate, account_activation_sent, user_login, logout, profile, profile_edit, password_change, password_reset, password_reset_confirm, password_reset_complete
from django.contrib.auth import views



app_name = 'sessions'

urlpatterns = [
    path('register/', register, name='register'),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate'),
    path('account_activation_sent/', account_activation_sent, name='account_activation_sent'),
    path('login/', user_login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
    # path('profile_edit/', profile_edit, name='profile_edit'),
    # path('password_change/', password_change, name='password_change'),
    # path('password_reset/', password_reset, name='password_reset'),
    # path('password_reset_confirm/', password_reset_confirm, name='password_reset_confirm'),
    # path('password_reset_complete/', password_reset_complete, name='password_reset_complete'),
]

House Of Young/core/models.py
from collections.abc import Iterable
import logging
import qrcode
from qrcode.exceptions import DataOverflowError
from io import BytesIO
from django.core.files import File
from PIL import Image, ImageDraw
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
from django.contrib.auth import get_user_model

logger = logging.getLogger(__name__)

class Organizer(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class QRCodeMixin(models.Model):
    qr_code = models.ImageField(upload_to='qr_codes', blank=True)

    def generate_qr_code(self, data):
        try:
            qrcode_img = qrcode.make(data)
            canvas = Image.new('RGB', (290, 290), 'white')
            draw = ImageDraw.Draw(canvas)
            canvas.paste(qrcode_img)
            fname = f'qr_code-{self.sanitize_filename(data)}.png'
            buffer = BytesIO()
            canvas.save(buffer, 'PNG')
            self.qr_code.save(fname, File(buffer), save=False)
            canvas.close()
            logger.debug("QR code saved successfully.")
        except DataOverflowError as e:
            logger.error(f"Error generating QR code for {data}: {e}")
        except Exception as e:
            logger.error(f"Error saving QR code for {data}: {e}")
        finally:
            return self.qr_code

    def sanitize_filename(self, filename):
        return slugify(filename)

    class Meta:
        abstract = True

class Homepage(models.Model):
    event_date = models.DateTimeField(help_text='Date and time of the event')
    is_active = models.BooleanField(default=True, help_text='Check if the event is currently active')

    def __str__(self):
        return f"Homepage - {self.event_date}"

    class Meta:
        app_label = 'core'
        verbose_name_plural = 'Home Pages'
        ordering = ('-event_date',)

class Venue(models.Model):
    address = models.CharField(max_length=225)
    city = models.CharField(max_length=225)
    country = models.CharField(max_length=225)

    def __str__(self):
        return self.address

class Event(QRCodeMixin, models.Model):
    home_page = models.ForeignKey('core.HomePage', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='events/', blank=True)
    event_date = models.DateTimeField(help_text='Date of the event', null=True, blank=True, default=None)
    sponsor = models.ManyToManyField('Sponsor', related_name='event_sponsors', blank=True)
    collaborator = models.ManyToManyField('Collaborator', related_name='events', blank=True)
    organizer = models.ForeignKey(Organizer, on_delete=models.CASCADE, default=1)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE, default=1)  # Set default to a valid Venue instance
    tickets_available = models.PositiveIntegerField(default=0)
    qr_code = models.ImageField(upload_to='qr_codes', blank=True)
    ticket_price = models.DecimalField(max_digits=1000, decimal_places=2, default=0, help_text='€')
    is_published = models.BooleanField(default=True, help_text='Check if the event is published')
    slug = models.SlugField(max_length=255, unique=True, blank=True)


    def get_absolute_url(self):
        return reverse('core:event_detail', args=[str(self.id), self.slug])

    def save(self, *args, **kwargs):
        if not self.id:
            self.generate_qr_code(self.title)

        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class Collaborator(QRCodeMixin, models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    organizer = models.ForeignKey(Organizer, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='collaborators')
    qr_code = models.ImageField(upload_to='qr_codes/collaborators', blank=True)

    def save(self, *args, **kwargs):
        if not self.qr_code:
            self.generate_qr_code(self.user.username)
        super().save(*args, **kwargs)

    def __str__(self):
        username = self.user.username if self.user else 'Unknown User'
        organizer_name = self.organizer.name if self.organizer else 'Unknown Organizer'
        event_title = self.event.title if self.event else 'Unknown Event'
        return f"{username} - {organizer_name} - {event_title}" if all([username, organizer_name, event_title]) else 'Incomplete Collaborator'



class Session(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def __str__(self):
        return self.title

class Sponsor(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    logo = models.ImageField(upload_to='sponsor_logos/')
    events = models.ManyToManyField(Event, related_name='sponsors')

    def __str__(self):
        return self.name

class BlogPost(models.Model):
    title = models.CharField(max_length=100)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True, null=True, related_name='blog_posts')
    image = models.ImageField(upload_to='blog_posts/')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=True, help_text='Check if the blog post is published')
    slug = models.SlugField(max_length=255, unique=True, blank=True)

    def get_absolute_url(self):
        return reverse('core:blog_detail', args=[str(self.id), self.slug])

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Blog Posts'
        ordering = ('-created_at',)

class Attendee(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    events_attending = models.ManyToManyField(Event, related_name='attendees')

    def __str__(self):
        return self.user.username

SHAPE_CHOICES = (
    ('1', 'Cube'),
    ('2', 'Sphere'),
    ('3', 'Torus'),
    ('4', 'Cylinder'),
    ('5', 'Plane'),
    ('6', 'Heart'),
    ('7', 'Dodecahedron'),
    ('8', 'Octahedron'),
    ('9', 'Icosahedron'),
    ('10', 'Tetrahedron'),
    ('11', 'Ring'),
    ('12', 'Knot'),
    ('13', 'Polyhedron'),
    ('14', 'TorusKnot'),
    ('15', 'Stars')
)

class Webgel(models.Model):
    type = models.CharField(max_length=3, choices=SHAPE_CHOICES)
    color = models.CharField(max_length=7, help_text='Hex color code')

    def __str__(self):
        return str(self.id)

House Of Young/core/api/views.py
from rest_framework import status
from rest_framework import serializers
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from ..models import Event
from ..views import get_active_home_page
from .serializers import EventSerializer
from .utils import generate_qr_code

class EventViewSet(ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer

    def perform_create(self, serializer):
        home_page = get_active_home_page()
        if home_page:
            serializer.save(home_page=home_page)
        else:
            raise serializers.ValidationError("No active Homepage available")


    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        self.perform_create(serializer)

        event = serializer.save()

        if not event.qr_code:
            qr_code = generate_qr_code(request.data['title'], request.data['date'])
            event.qr_code = qr_code
            event.save()

        return Response(serializer.data, status=status.HTTP_201_CREATED)

House Of Young/core/views.py
import logging
import json
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from django.db.models import Q
from .models import BlogPost, Event, Webgel
from .config import HOMEPAGE_CONTENT
from django.contrib.auth.decorators import login_required

logger = logging.getLogger(__name__)

def get_active_home_page():
    return HOMEPAGE_CONTENT

def index(request):
    webgel = [{'type': int(x.type), 'color': x.color} for x in Webgel.objects.all()]
    webgel_json = json.dumps(webgel)
    home_page = get_active_home_page()

    if home_page:
        events = Event.objects.filter(Q(home_page=True) | Q(sponsors=True)).order_by('event_date')
        now = timezone.localtime(timezone.now())
        upcoming_events = events.filter(event_date__gte=timezone.localtime(timezone.now()).replace(microsecond=0))[:3]
        upcoming_events = events.filter(event_date__gte=timezone.localtime(timezone.now()))[:3]
        past_events = events.filter(event_date__lt=timezone.now()).order_by('-event_date')[:1]
        recent_blog_posts = BlogPost.objects.filter(is_published=True).order_by('-created_at')[:3]
        context = {
            'home_page': home_page,
            'upcoming_events': upcoming_events,
            'past_events': past_events,
            'blog_posts': recent_blog_posts,
            'webgel': webgel_json,
        }
        return render(request, 'core/index.html', context)
    else:
        logger.error("No active home page found.")
        return HttpResponse("No active home page found.")


def blog(request):
    blog_posts = BlogPost.objects.filter(is_published=True).order_by('-created_at')
    return render(request, 'core/blog.html', {'blog_posts': blog_posts})

def blog_detail(request, blog_id):
    blog_post = get_object_or_404(BlogPost, id=blog_id)
    return render(request, 'core/blog_detail.html', {'blog_post': blog_post})

def blog_list(request):
    blog_posts = BlogPost.objects.filter(is_published=True).order_by('-created_at')
    return render(request, 'core/blog_list.html', {'blog_posts': blog_posts})

def event(request):
    home_page = get_active_home_page()

    if home_page:
        events = Event.objects.filter(Q(home_page=True) | Q(sponsors=True)).order_by('event_date')
        upcoming_events = events.filter(event_date__gte=timezone.now())[:3]
        past_events = events.filter(event_date__lt=timezone.now()).order_by('-event_date')[:5]
        unique_venue = Event.objects.values_list('venue', flat=True).distinct()
        unique_sponsor = Event.objects.exclude(sponsor__isnull=True).values_list('sponsor', flat=True).distinct()
        unique_collaborator = Event.objects.exclude(collaborator__isnull=True).values_list('collaborator', flat=True).distinct()
        return render(request, 'core/event.html', {'upcoming_events': upcoming_events, 'past_events': past_events, 'unique_collaborator': unique_collaborator})
    else:
        logger.error("No active home page found.")
        return HttpResponse("No active home page found.")

@login_required
def event_detail(request, event_id):
    event = get_object_or_404(Event, id=event_id, slug=request.GET.get("slug"))
    blogs = BlogPost.objects.filter(event=event)
    collaborators = Event.objects.exclude(collaborator__isnull=True).values_list('collaborator', flat=True).distinct()
    sponsors = Event.objects.exclude(sponsor__isnull=True).values_list('sponsor', flat=True).distinct()


    favourite = request.user.profile.favourites.filter(id=event_id).exists() if hasattr(request.user, 'profile') else False

    return render(request, "core/event_detail.html", {
        "event_id": event_id,

        "event": event,
        "blogs": blogs,
        "collaborators": collaborators,
        "sponsors": sponsors,
        "favourite": favourite,
    })

def about(request):
    if request.method == 'POST':
        pass
    return render(request, 'core/about.html')

def contact(request):
    if request.method == 'POST':
        pass
    return render(request, 'core/contact.html')

House Of Young/core/templates/core/about.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}About{% endblock %}

{% block scripts %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.min.js'></script>



{% endblock %}

{% block content %}
<div id="webgel">
  <section class="section__container about__container">
    <h2 class="section__header">ABOUT US</h2>
    <p class="section__subheader">
      Welcome to House Of Young – more than just an event platform.
      We are seasoned experts in the realms of branding, management,
      organization, and the cultivation of brands, artists, and more.
      Our strength lies in our diversity, coupled with over a decade
      of experience. With a team of specialists boasting unique and
      substantial abilities, we deliver unparalleled excellence.
      Our commitment goes beyond event hosting. House Of Young is your
      gateway to a world where expertise converges with creativity.
      We specialize in crafting extraordinary experiences,
      fostering talent, and building lasting connections.
      Whether you're an artist seeking exposure, an enthusiast
      craving unique events, or a brand aiming to make a statement –
      House Of Young is your definitive destination.
      Join us in this journey where passion meets proficiency,
      and together, we create moments that resonate.
    </p>
    <div class="about__image">
      <img src="{% static 'images/HOY-removebg-preview.png' %}" alt="HOY">
      <div class="about__grid">
        <div class="about__card">
          <span><i class="ri-user-star-fill"></i></span>
          <div class="about__card__content">
            <h4>Classy Lifestyle</h4>
            <p>Lifestyle management lke no other.
              We are the best in the game.</p>
            </p>
          </div>
        </div>
        <div class="about__card">
          <span><i class="ri-vidicon-fill"></i></span>
          <div class="about__card__content">
            <h4>Unforgettable Events</h4>
            <p>Events organization and purification.</p>
          </div>
        </div>
        <div class="about__card">
          <span><i class="ri-building-line"></i></span>
          <div class="about__card__content">
            <h4>Good Management</h4>
            <p>Supportive management, brands.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="review">
    <div class="section__container review__container">
      <span><i class="ri-double-quotes-r"></i></span>
      <div class="review__content">
        <h4>REVIEWS</h4>
        <p>
          The best
        </p>
        <div class="review__rating">
          <span><i class="ri-star-fill"></i></span>
          <span><i class="ri-star-fill"></i></span>
          <span><i class="ri-star-fill"></i></span>
          <span><i class="ri-star-fill"></i></span>
          <span><i class="ri-star-half-fill"></i></span>
        </div>
        <div class="review__footer">
          <div class="review__member">
            <img src="{% static 'images/Davido_performing_at_the_Lagos_city_Marathon_gala_2020_10_27_05_793000_(cropped).jpeg' %}" alt="HOY">
            <div class="review__member__details">
              <h4>Jane Cooper</h4>
              <p>Software Developer</p>
            </div>
          </div>
          <div class="review__nav">
            <span><i class="ri-arrow-left-line"></i></span>
            <span><i class="ri-arrow-right-line"></i></span>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

{% endblock %}

House Of Young/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block title %}{% endblock %} | House Of Young</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon@3.4.0/fonts/remixicon.css"rel="stylesheet"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  <link rel="stylesheet" href="{% static 'stylesheet/applications.css' %}">
  <link rel="stylesheet" href="{% static 'stylesheet/accounts.css' %}">
  {% block scripts %}{% endblock %}
  <script defer type='module' src="{% static 'javascript/script.js' %}"></script>
</head>

<body>
  <nav>
    <div class="nav__logo">
      <a href="{% url 'core:index' %}" class="logo"><img src="{% static 'images/HOY-removebg-preview.png' %}" alt="logo"></a>
    </div>
    <ul class="nav__links">
      <li class="link"><a href="{% url 'core:event' %}">Events</a></li>
      <li class="link"><a href="{% url 'core:blog_list' %}">Blogs</a></li>
      <li class="link"><a href="{% url 'core:about' %}">About</a></li>
      <li class="link"><a href="{% url 'core:contact' %}">Work with Us</a></li>
    </ul>
    <button id="btn" class="btn">
      {% if request.user.is_authenticated %}
        <a href="{% url 'sessions:logout' %}" class="account">Logout</a>
      {% else %}
        <a href="{% url 'sessions:register' %}" class="account">Sign Up</a>
        <a href="{% url 'sessions:login' %}" class="account">Login</a>
      {% endif %}
    </button>
  </nav>





  {% block content %}





  <section id="webgel" class="webgel">
    <canvas></canvas>
  </section>







  <script defer type='module' src="{% static 'javascript/app.js' %}"></script>
  <script defer type='module' src="{% static 'javascript/script.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.4/gsap.min.js"
    integrity="sha512-EZI2cBcGPnmR89wTgVnN3602Yyi7muWo8y1B3a8WmIv1J9tYG+udH4LvmYjLiGp37yHB7FfaPBo8ly178m9g4Q=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.4/CSSRulePlugin.min.js"
    integrity="sha512-aUM9IHJr7TYwzhhbK0G9UQX6WNq6/1HC+lsh+EuqJyaOB44csmHMRVHcIVMWfrruvpVTtEqshD28L+0XxMH//g=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>

  {% endblock %}

</body>

</html>

House Of Young/core/templates/core/blog.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}Blog{% endblock %}

{% block scripts %}

<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.min.js'></script>

{% endblock %}

{% block content %}

<div id="webgel">
  
</div>

{% endblock %}

House Of Young/core/templates/core/blog_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}{{ blog_post.title }}{% endblock %}



{% block scripts %}

<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.min.js'></script>

{% endblock %}

{% block content %}

<div id="webgel">

</div>

{% endblock %}

House Of Young/core/templates/core/blog_list.html
{% extends 'core/base.html' %}

{% load static %}


{% block title %}Blog{% endblock %}

{% block scripts %}

<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.min.js'></script>

{% endblock %}

{% block content %}

<div id="webgel">

</div>

{% endblock %}

House Of Young/core/templates/core/index.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Home{% endblock %}

{% block scripts %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.min.js'></script>
{% endblock %}

{% block content %}

<div id="webgel" class="webgel">
  <header class="section__container header__container row">
      <div class="header__content">
        <span class="bg__blur"></span>
        <span class="bg__blur header__blur"></span>
        <h4>HOUSE OF YOUNG</h4>
        <h1><span>WE CURATE & MANAGE</span> BUSINESSES  ONLINE.</h1>
        <p style="margin: 2rem 0;">
          House of Young is more than just an event organizing platform;
          it's an organization dedicated to nurturing, building, and
          fostering the growth of entrepreneurs and small businesses.
          We provide them with a platform and a voice to showcase their
          talents, allowing them to reach a wider audience and have their
          abilities discovered. Our expertise, rooted in event organization
          and collaboration, is focused on establishing a significant presence,
          not only in Valencia, Spain, but also in Nigeria—the largest and most
          vibrant hub of events in Africa—before expanding our influence globally.
        </p>
        <a href="{% url 'core:event' %}" class="btn">Explore Our Events</a>
      </div>
    <div class="header__image">
      <img src="{% static 'images/HOY-removebg-preview.png' %}" alt="image"></a>
    </div>

    <section class="section__container events__container">
      <h2 class="section__header">Upcoming Events</h2>
      <div class="explore__grid-home">
        {% for event in upcoming_events %}
        <div class="explore__card">
          <span><i class="ri-boxing-fill"></i></span>
          <h4 class="text-xl font-semibold mb-2" style="text-align: center;">{{ event.title }}</h4>
          <p class="text-gray-500" style="margin-left: 0em; margin-bottom: 3em;">Date and Time: {{ event.event_date }} {{ event.event_time }}</p>
          <p class="text-gray-500" style="margin-left: 0em; margin-bottom: 3em;">Venue: {{ event.venue }}</p>
          <a href="/event/{{ event.id }}" target="_blank" class="btn btn-primary" style="margin: 0 2em;">View Event</a>
          {% if event.image %}
            <img src="{{ event.image.url }}" alt="{{ event.title }} Image" class="event__image">
          {% endif %}
          {% if event.blog_post.slug %}
            <a href="{% url 'blog_post_detail' slug=event.blog_post.slug %}" class="btn">Read More</a>
          {% endif %}
        </div>
        {% endfor %}
        {% if upcoming_events|length == 0 %}
          <p class="text-gray-500" style="margin-left: 0em; margin-bottom: 3em;">No upcoming events</p>
        {% endif %}
      </div>

      <h2>Past Events</h2>
      {% for event in past_events %}
          <div class="explore__card">
            <span><i class="ri-boxing-fill"></i></span>
            <h4 class="text-xl font-semibold mb-2" style="text-align: center;">{{ event.title }}</h4>
            <p class="text-gray-500" style="margin-left: 0em; margin-bottom: 3em;">Date : {{ event.event_date }}</p>
            <p class="text-gray-500" style="margin-left: 0em; margin-bottom: 3em;">Time: {{ event.event_time }}</p>
            <p class="text-gray-500" style="margin-left: 0em; margin-bottom: 3em;">Venue: {{ event.venue }}</p>
            <a href="/event/{{ event.id }}" target="_blank" class="btn btn-primary" style="margin: 0 12em;">View Event</a>
            {% if event.image %}
              <img src="{{ event.image.url }}" alt="{{ event.title }} Image" class="event__image">
            {% endif %}
            {% if event.blog_post.slug %}
              <a href="{% url 'blog_post_detail' slug=event.blog_post.slug %}" class="btn">Read More</a>
            {% endif %}
          </div>
        {% endfor %}
    </section>
  </header>


  <footer class="section__container footer__container">
    <span class="bg__blur"></span>
    <span class="bg__blur footer__blur"></span>
    <div class="footer__col">
      <div class="footer__logo"><a href="{% url 'core:index' %}" class="logo"><img src="{% static 'images/HOY-removebg-preview.png' %}" alt="logo"></a></div>
      <p>
        House of Young is more than just an event organizing platform;
        it's an organization dedicated to nurturing, building, and
        fostering the growth of entrepreneurs and small businesses.
      </p>
      <div class="footer__socials">
        <a href="#"><i class="ri-facebook-fill"></i></a>
        <a href="#"><i class="ri-instagram-line"></i></a>
        <a href="#"><i class="ri-twitter-fill"></i></a>
      </div>
    </div>
    <div class="footer__col">
      <h4>Company</h4>
      <a href="#">Business</a>
      <a href="#">Franchise</a>
      <a href="#">Partnership</a>
      <a href="#">Network</a>
    </div>
    <div class="footer__col">
      <h4>About Us</h4>
      <a href="#">Blogs</a>
      <a href="#">Subscriptions</a>
      <a href="#">Security</a>
      <a href="#">Careers</a>
    </div>
    <div class="footer__col">
      <h4>Contact</h4>
      <a href="#">Contact Us</a>
      <a href="#">Privacy Policy</a>
      <a href="#">Terms & Conditions</a>
    </div>
  </footer>
  <div class="footer__bar">
    Copyright © 2024 | House Of Young. All rights reserved.
  </div>

</div>

{% endblock %}

House Of Young/core/templates/core/post.html
{% extends 'core/base.html' %}

{% block title %}{{ blog_post.title }}{% endblock %}

{% block scripts %}
{% comment %} threejs link {% endcomment %}
<script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/0.160.0/three.min.js'></script>

<script>
  const webgel = '{{ webgel | safe }}';
  if (webgel.trim() !== '') {
    const parsedData = JSON.parse(webgel);
    console.log(parsedData);
  } else {
    console.error('The webgel variable is empty.');
  }

</script>


{% endblock %}

{% block content %}

<div id="webgel" class="webgel" style="position: fixed; top: 0; left: 0;">
  <div class="row" style="position: absolute; color: gold;">
    <article>
        <h2>{{ blog_post.title }}</h2>
        <p>{{ blog_post.content }}</p>
        <!-- Add other details as needed -->
    </article>
    <section>
        <h3>Related Events</h3>
        {% for event in related_events %}
            <!-- Display related events -->
        {% endfor %}
    </section>
  </div>

</div>
{% endblock %}